FROM ghcr.io/linuxcontainers/alpine:latest AS builder

# redeclipse reference
ARG RE_REF
# redeclipse commit sha
ARG RE_COMMIT=""

# get dependencies
RUN apk update && \
    apk add --no-cache gcc g++ zlib-dev git ca-certificates coreutils make

# checkoout source code
RUN git init /redeclipse && \
    cd /redeclipse && \
    git remote add origin https://github.com/redeclipse/oldsvnre.git && \
    git sparse-checkout init --no-cone && \
    git sparse-checkout set --no-cone "*" "!/data/**" "/data/config/**" "!/game/mek/**" "!/src/site/**" && \
    git fetch --depth 1 --filter=blob:none origin "${RE_REF}" && \
    git reset --hard FETCH_HEAD

WORKDIR /redeclipse

# build server
RUN make install-server \
        INSTDIR="/redeclipse/bin/native/" \
        CFLAGS="-O3 -fomit-frame-pointer -ffast-math -fno-finite-math-only -funroll-loops -flto" \
        CXXFLAGS="-O3 -fomit-frame-pointer -ffast-math -fno-finite-math-only -funroll-loops -flto" \
        LDFLAGS="-O3 -flto" \
        -O -j$(nproc) -C src && \
    mv ./bin/native/redeclipse_server_native ./bin/native/redeclipse_server_linux

FROM ghcr.io/linuxcontainers/alpine:latest

# redeclipse commit sha
ARG RE_COMMIT=""

LABEL org.opencontainers.image.title="Red Eclipse Server"
LABEL org.opencontainers.image.licenses="LicenseRef-Red-Eclipse-License"
LABEL org.opencontainers.image.authors="Iceflower S <iceflower@iceflower.eu>"
LABEL org.opencontainers.image.vendor="Iceflower S <iceflower@iceflower.eu>"
LABEL org.opencontainers.image.base.name="ghcr.io/linuxcontainers/alpine:latest"
LABEL org.opencontainers.image.revision="${RE_COMMIT}"

# add server user and set permissions
RUN adduser -S -D redeclipse && \
    mkdir /redeclipse && \
    chown redeclipse: -R /redeclipse

# create required directories and install dependencies
RUN apk update && \
    apk add --no-cache libstdc++ && \
    mkdir -p /redeclipse/bin/native && \
    mkdir -p /redeclipse/data/ && \
    mkdir -p /re-server-config/home && \
    mkdir -p /re-server-config/package && \
    mkdir -p /re-server-config/sauer

COPY --from=builder /redeclipse/bin/native/ /redeclipse/bin/native/
COPY --from=builder /redeclipse/data/ /redeclipse/data/
COPY --from=builder /redeclipse/game/ /redeclipse/game/

USER redeclipse

WORKDIR /redeclipse
ENTRYPOINT ["./bin/native/redeclipse_server_linux"]
CMD ["-h/re-server-config/home/", "-p/re-server-config/package/", "-o/re-server-config/sauer/"]
